name: diffenv
channels:
  - defaults
dependencies:
  - tzdata==2023c
  - libstdcxx-ng==11.2.0
  - zstd==1.5.5
  - libffi==3.4.4
  - six==1.16.0
  - libuuid==1.41.5
  - tk==8.6.12
  - libedit==3.1.20221030
  - pyopenssl==23.0.0
  - libssh2==1.10.0
  - readline==8.2
  - reproc==14.2.4
  - requests==2.29.0
  - libnghttp2==1.52.0
  - toolz==0.12.0
  - ca-certificates==2023.05.30
  - pybind11-abi==4
  - ncurses==6.4
  - jsonpatch==1.32
  - conda-package-handling==2.1.0
  - sqlite==3.41.2
  - libev==4.33
  - wheel==0.38.4
  - libcurl==8.1.1
  - libgomp==11.2.0
  - ruamel.yaml==0.17.21
  - packaging==23.0
  - icu==58.2
  - libxml2==2.10.3
  - pysocks==1.7.1
  - ld_impl_linux-64==2.38
  - certifi==2023.5.7
  - idna==3.4
  - pycparser==2.21
  - reproc-cpp==14.2.4
  - xz==5.4.2
  - openssl==3.0.9
  - tqdm==4.65.0
  - pcre2==10.37
  - conda==23.5.2
  - conda-libmamba-solver==23.5.0
  - _libgcc_mutex==0.1
  - zstandard==0.19.0
  - cffi==1.15.1
  - conda-package-streaming==0.8.0
  - libmambapy==1.4.1
  - fmt==9.1.0
  - charset-normalizer==2.0.4
  - pluggy==1.0.0
  - python==3.11.4
  - boltons==23.0.0
  - krb5==1.20.1
  - c-ares==1.19.0
  - jsonpointer==2.1
  - pycosat==0.6.4
  - urllib3==1.26.16
  - _openmp_mutex==5.1
  - pip==23.1.2
  - cryptography==39.0.1
  - conda-content-trust==0.1.3
  - libgcc-ng==11.2.0
  - lz4-c==1.9.4
  - yaml-cpp==0.7.0
  - bzip2==1.0.8
  - libarchive==3.6.2
  - zlib==1.2.13
  - setuptools==67.8.0
  - brotlipy==0.7.0
  - libmamba==1.4.1
  - libsolv==0.7.22
